name: dsc_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  introduction_screen: ^2.1.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  font_awesome_flutter: ^9.1.0
  smooth_page_indicator: ^1.0.0+2
  intl:
  chips_choice_null_safety: ^2.0.4
  animated_splash_screen: ^1.1.0
  page_transition: ^2.0.1-nullsafety.0
  flutter_staggered_animations: ^1.0.0
  timeago: ^3.1.0
  flutter_html: ^2.1.5
  webview_flutter: ^2.3.0
  infinite_scroll_pagination:
  flutter_svg: ^0.23.0+1
  url_launcher:
  fluttertoast:
  device_info_plus:
  iconsax:
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/
    - assets/icons/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900

